[package]
name = "rdate"
version = "0.1.0"
edition = "2021"
authors = ["takeweb takeweb@mac.com"]
description = "cat command wrtten by Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.34"
